// comments
export const ADD_COMMENT = "ADD_COMMENT"
export const ADD_COMMENTS = "ADD_COMMENTS"
export const FAILED_COMMENTS  = "FAILED_COMMENTS"

// dish
export const LOADING_DISHES = "LOADING_DISHES"
export const ADD_DISHES = "ADD_DISHES"
export const UPADTE_DISH = "UPADTE_DISH"
export const FAILED_DISHES  = "FAILED_DISHES"

// leaders
export const LOADING_LEADERS = "LOADING_LEADERS"
export const ADD_LEADERS = "ADD_LEADERS"
export const FAILED_LEADERS  = "FAILED_LEADERS"

// promotions
export const LOADING_PROMOTIONS = "LOADING_PROMOTIONS"
export const ADD_PROMOTIONS = "ADD_PROMOTIONS"
export const FAILED_PROMOTIONS  = "FAILED_PROMOTIONS"

// auth
export const REQUEST_LOGIN = "EQUEST_LOGIN"
export const SUCCESS_LOGIN = "SUCCESS_LOGIN"
export const FAILED_LOGIN  = "FAILED_LOGIN"
export const REQUEST_LOGOUT  = "REQUEST_LOGOUT"
export const SUCCESS_LOGOUT  = "SUCCESS_LOGOUT"
